In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

#countries dataset
df1 = pd.read_csv('/content/drive/MyDrive/Colab/countries.csv')

#
df1.columns = [col.strip().lower().replace(' ', '_') for col in df1.columns]
df1.columns = [col.strip().lower().replace('-', '_') for col in df1.columns]


#df[df['alpha_2'].isna()]
df1['alpha_2'] = df1['alpha_2'].fillna('NA')
#df[df['region'].isna()]
df1['region'] = df1['region'].fillna('NA')

df1['region'] = df1['region'].fillna('Antarctic')
df1['sub_region'] = df1['sub_region'].fillna('Southern Hemishpere')

df1['name'] = df1['name'].str.strip().str.upper()
df1['alpha_2'] = df1['alpha_2'].str.strip().str.upper()
df1['alpha_3'] = df1['alpha_3'].str.strip().str.upper()
df1['region'] = df1['region'].str.strip().str.upper()
df1['sub_region'] = df1['sub_region'].str.strip().str.upper()
df1.rename(columns={'alpha_3': 'country_code'}, inplace=True)




df1.head()

#df.dtypes
#df.isna().sum()
#df.head(248)
#count = df['name'].count()
#count_unique = df['name'].nunique()
#print(count_unique)
#df.describe
#print(count)

Mounted at /content/drive

             name alpha_2 country_code   region       sub_region
0     AFGHANISTAN      AF          AFG     ASIA    SOUTHERN ASIA
1   ÅLAND ISLANDS      AX          ALA   EUROPE  NORTHERN EUROPE
2         ALBANIA      AL          ALB   EUROPE  SOUTHERN EUROPE
3         ALGERIA      DZ          DZA   AFRICA  NORTHERN AFRICA
4  AMERICAN SAMOA      AS          ASM  OCEANIA        POLYNESIA

DATA OVERVIEW COMPLETED
DATA CLEANING COMPLETED

The **countries file** has data on 249 countries with a 2 letter abbreviation represented in the *alpha_2* colomn. Next there's  a 3 letter abbreviation is the colomn *alpha_3*.
There's also information on the region and subregion that each country is in.
This tables key that connects it to the remaining two datasets are **countires.alpha_3** and **events.country_code**.

In [ ]:
import pandas as pd
df2 = pd.read_csv('/content/drive/MyDrive/Colab/events.csv')

df2.columns = [col.strip().lower().replace(' ', '_') for col in df2.columns]

df2['country_code'] = df2['country_code'].str.strip().str.upper()
df2['sales_channel'] = df2['sales_channel'].str.strip().str.upper()
df2.head()

df2['country_code'] = df2['country_code'].fillna('UNKNOWN')

df2[df2['units_sold'].isna()]
df2['units_sold'] = df2['units_sold'].fillna('UNKNOWN')
df2['order_date'] = pd.to_datetime(df2['order_date'])
df2['ship_date'] = pd.to_datetime(df2['ship_date'])
df2['units_sold'] = pd.to_numeric(df2['units_sold'], errors='coerce')

df2['order_priority'] = df2['order_priority'].str.strip().str.upper()



#df2.isna().sum()
#df2.head(248)
#df2.dtypes
df2.head(248)
#df2.isna().sum()

,order_id,order_date,ship_date,order_priority,country_code,product_id,sales_channel,units_sold,unit_price,unit_cost
0,100640618,2014-10-08,2014-10-18,M,NOR,2103,ONLINE,650.0,205.70,117.11
1,100983083,2016-08-11,2016-08-11,C,SRB,2103,OFFLINE,1993.0,205.70,117.11
2,101025998,2014-07-18,2014-08-11,M,UNKNOWN,7940,ONLINE,4693.0,668.27,502.54
3,102230632,2017-05-13,2017-06-13,L,MNE,2455,ONLINE,1171.0,109.28,35.84
4,103435266,2012-08-11,2012-09-18,H,SRB,1270,OFFLINE,7648.0,47.45,31.79
...,...,...,...,...,...,...,...,...,...,...
243,261640536,2015-06-22,2015-08-01,M,BIH,7940,OFFLINE,4104.0,668.27,502.54
244,262177836,2012-12-06,2013-01-16,H,ESP,4594,OFFLINE,3103.0,9.33,6.92
245,263098371,2014-06-08,2014-07-04,L,MCO,3127,ONLINE,5509.0,81.73,56.67
246,263427960,2011-08-06,2011-09-20,H,AUT,4594,OFFLINE,3042.0,9.33,6.92
247,263647687,2012-03-23,2012-03-30,M,UNKNOWN,2455,ONLINE,8064.0,109.28,35.84

DATA OVERVIEW COMPLETED
DATA CLEANING COMPLETED

The file **events** display data on orders placed both online and offline. The data also shows detailed information on when orders are being placed, and the math behind the products being sold.This table in connect to both the products dataset and countries dataset. This tables key that connects it to the remaining two datasets are **products.id** and **events.product_id**. Also, **events.country_code** and **countries.alpha_3**.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df3 = pd.read_csv('/content/drive/MyDrive/Colab/products.csv')
df3['item_type'] = df3['item_type'].str.strip().str.upper()
df3.rename(columns={'id': 'product_id'}, inplace=True)

#df3.isna().sum()
df3.head()
#df3.dtypes

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   product_id        item_type
0        2103           CEREAL
1        7940        HOUSEHOLD
2        2455          CLOTHES
3        1270        BEVERAGES
4        8681  OFFICE SUPPLIES

DATA OVERVIEW COMPLETED
DATA CLEANING COMPLETED

The **products** file display information on the item type to help identify which category the items are in.
This tables key that connects it to the remaining two datasets are **products.id** and **events.product_id**.

The company prcessed over 1,330 orders, generating over 1.7 Billion dollars in revenue and $501,434,459.00 in profit.

In [ ]:
import matplotlib.pyplot as plt

#df = countries
#df2 = events
#df3 = products

df = df2.merge(df3, on = 'product_id', how = 'left')
df = df.merge(df1, on = 'country_code', how = 'left')

total_orders = df['order_id'].nunique()
total_revenue = (df['units_sold'] * df['unit_price']).sum()

df['profit_per_item'] = (df['unit_price'] - df['unit_cost']) * df['units_sold']
total_profit = df['profit_per_item'].sum()

total_countries = df['country_code'].nunique()
total_regions = df['region'].nunique()

total_cost = (df['unit_cost'] * df['units_sold']).sum()

print(f'Total Profit: ${total_profit}')
print(f'Total Orders: {total_orders}')
print(f'Total Revenue: ${total_revenue}')
print(f'Total Countries: {total_countries}')
print(f'Total Regions: {total_regions}')


df['shipping_time'] = (df['ship_date'] - df['order_date']).dt.days
average_shipping_time = df['shipping_time'].mean()
print(f'Average Shipping Time: {average_shipping_time} days')
df['day'] = df['order_date'].dt.day_name()

df['revenue'] = df['units_sold'] * df['unit_price']
df['total_cost'] = df['units_sold'] * df['unit_cost']
df['profit'] = df['revenue'] - df['total_cost']
#df.groupby('name')['profit'].sum()
#df.groupby('sales_channel')['revenue'].sum()
#df.groupby('day')['revenue'].sum()

#revenue_per_country = df.groupby('name')['revenue'].sum()
#profit_per_country = df.groupby('name')['profit'].sum()
#country_summary = df.groupby('name').agg({
    #'revenue': 'sum',
    #'profit': 'sum'
#}).reset_index()
#print(country_summary)

avg_shipping_overall = df['shipping_time'].mean()
print("Average Shipping Time Overall:", avg_shipping_overall)

# Group by sales channel
channel_summary = df.groupby('sales_channel').agg({
    'revenue':'sum',
    'profit':'sum'
}).reset_index()

print(channel_summary)

#df.groupby('item_type')['revenue'].sum().plot(kind='bar')
#plt.show()
#df['shipping_time'].plot(kind='hist')
#plt.show()
#df.resample('M', on='order_date')['revenue'].sum().plot()

print(f'Total Cost: ${total_cost}')
#df.isna().sum()
#df.dtypes
#df.head(248)
#df.head(248)

Total Profit: $501434459.0
Total Orders: 1330
Total Revenue: $1702129408.21
Total Countries: 46
Total Regions: 2
Average Shipping Time: 24.77593984962406 days
Average Shipping Time Overall: 24.77593984962406
  sales_channel       revenue        profit
0       OFFLINE  8.717606e+08  2.534665e+08
1        ONLINE  8.303688e+08  2.479679e+08
Total Cost: $1200694949.2099998

**Where the company stands:**

The company processed a total of *1,330* orders across *46 countries and 2 regions*, indicating a vast international presence.

The company generated **approximately 1.70 billion** in revenue and **$501.4 million in profit**. Total cost peaked at **1.2 billion**.


From my analysis, this results in a profit margin of about **29%**, suggesting the company is operating well and keeping costs down as it relates to revenue.

**What's Working Well**:

The company is overall doing well and here are some areas that are being highlighted for the contribution to revenue and more importantly, profit.

**Office Supplies**, **household**, and **cosmetics** generate the highest revenue.


**Office Supplies** + *$77,977,176*

**Cosmetics** = *$92,723,306*

**Household** = *$72,962,467*


These three categories have strong margins,and cosmetics has the highest margin. Combined, these 3 category contribute almost **50%** of the company's total profit. These categories are drivers of the performance.

Categories like **Office Supplies**, **Beverages**, and **Clothes** have the highest sales volume, which helps support the revenue.

**Offline** & **Online** sales are bringing in relatively the same amount of profit, indicating that the company isn't relying on either sales channel.

Geographically, performance in countries like **Ukraine**, **Czech Republic**, and **Malta** bring in great profit contribution. Some smaller countries, like **San Marino*, bring in generally high profits, which is noteworthy.

The customer's purchasing pattern shows that the highest purchasing days are **Mondays** and **Fridays**, marking the beginning and end of the week.

**Areas for Improvement**
The company is doing well overall, but there are a few areas where improvements might help.

The **average shipping** time is around **25 days**, which feels quite long. Shortening this time could improve customer satisfaction.

Some product categories, like **Fruits** and **Beverages**, sell a lot but bring in less revenue and profit. This might mean their prices are low, or profit margins are small. Changing prices or customer costs could help.

Sales are also lower on **Tuesdays** and **Thursdays**. Running promotions or marketing on these days might boost sales during slower times.

Highlights:

- $1.7B in revenue



- $501.4M in profit

- 29% profit margin

- Sales channels are balanced between online and offline platforms.

- Sales channels are evenly balanced between online and offline platforms.

- The company operates in 46 countries across 2 regions

- The highest sales occur on Mondays and Fridays.



Top 3 performing item category in profit

- Cosmetics

- Household

- Office Supplies